// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Website_QLPT.Data;

#nullable disable

namespace Website_QLPT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316084500_AddTenantIdentityUserLinkAndInvoiceConstraints")]
    partial class AddTenantIdentityUserLinkAndInvoiceConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
